### ISSUE TITLE
Saved model for PyTorch 1.2?

### ISSUE THREAD

**Issue by plateau-n** [padmalcom/Real-Time-Voice-Cloning-German#1]
Hi, I would love to test the voice cloning for German language. Apparently your saved model "my_run.pt" has been created with PyTorch 1.6 as it is a Zip file. Any chance to get this model as a 1.2 version, too? If I update to 1.6 I get some crude exceptions.

**Comment by padmalcom** [comment]
Hi, unfortunately I cannot retrain a model for each pytorch version, it takes about 5 days. Furthermore, I could not find a converter. What exactly are the exceptions you get?

**Comment by plateau-n** [comment]
Hi, thank you for the quick reply. the exceptions I get is:
  File "C:\Users\Tom\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\serialization.py", line 559, in _load
    raise RuntimeError("{} is a zip archive (did you mean to use torch.jit.load()?)".format(f.name))
RuntimeError: **encoder\saved_models\my_run.pt is a zip archive (did you mean to use torch.jit.load()?)**

According to the forums the format of .pt changed to zip in version 1.6. When I install 1.6 I get even worse excpetions.

**Comment by ghost** [comment]
@padmalcom Here is an example of how you can convert torch models to the old format. This requires pytorch 1.6 or higher to be installed. The saved files will work with old and new versions of pytorch.

```
import torch
model = torch.load("encoder/saved_models/my_run.pt", map_location=torch.device("cpu"))
torch.save(model, "encoder/saved_models/my_run.pt", _use_new_zipfile_serialization=False)
```

**Comment by padmalcom** [comment]
Thank you @blue-fish, I think this is the answer that allows closing this issue.
