### ISSUE TITLE
No Issue. Just installed...

### ISSUE THREAD

**Issue by instant-high** [padmalcom/Real-Time-Voice-Cloning-German#13]
Thanks for that great work.
I've just installed, no problem.
German model working real good (release 0.2) with original demo_cli. (I've made a few changes, loading german model as default, changed infinite loop so loading and tests run only once before next text input)
Unfortunately german model need more VRAM?
Original english runs on GPU.
German version only on CPU. Not enough memory. (I only  have GTX1050 / 2 GB)

**Comment by padmalcom** [comment]
Hi, there are three models, which one are you talking about? Since this seems to be a lack of resource issue, I'm closing this one.
