### ISSUE TITLE
Voice cloning of males not reflected in result

### ISSUE THREAD

**Issue by eqikkwkp25-cyber** [padmalcom/Real-Time-Voice-Cloning-German#2]
First of all: Thank you for your adaptations made for the German language. 

You might close this issue as you trained the models on female voices and its expected that cloned voices from male audio samples sound like females too, right?

Btw, your code runs on Linux without issue (CLI version of demo), just needed to put symbols.py to a subfolder synthesizer/utils.

**Comment by padmalcom** [comment]
Hi, that's exactly the behavior you can expect, male voices sound female. I'll do the retraining again in January with both male and female voices but I'm afraid the current version will only work well when you clone female voices.
