### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by ichessebaeume1** [padmalcom/Real-Time-Voice-Cloning-German#24]
Ich habe bisher meinen Encoder und Synthesizer trainiert und alles lief gut. Meinen Encoder habe ich auf c.a 56000 Schritte trainiert und meinen Synthesizer auf c.a 30000 weil er ab da nicht mehr besser wurde. Das lief auch alles noch gut und es hat auch nicht allzu lang gedauert. Nun wollte ich aber das Preprocessing des Vocoders beginnen und nachdem alles Initialisiert ist und mein PC mit dem Preprocessing beginnt kriege ich nach immer genau 5 fertigen Dateien den folgenden Fehler:

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 28.00 MiB. GPU 0 has a total capacty of 6.00 GiB of which 0 bytes is free. Of the allocated memory 5.15 GiB is allocated by PyTorch, and 153.43 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Meiner GPU geht es vom Speicher her super sie läuft meistens bei 0,2-0,4 von 6GB. Ich habe auch schon versucht die Cache von PyTorch zu leeren leider vergeblichst. Ich habe gelesen das man die Größe des Models bzw. die Parameter einschränken kann um sowas zu verhindern weiß aber weder wie noch ob das etwas bringt

Ich würde mich über eine Antwort sehr freuen! LG Jonas

**Comment by padmalcom** [comment]
Hi Jonas, freut mich, dass du schon so weit gekommen bist. Das einfachste ist, die Batch Size des Trainings zu reduzieren. Die Architektur des Vocoders anzupassen, würde ich mir erst dafür aufheben, wenn ich gar nicht mehr weiterkomme. Mein nächster Ansatz wäre auch mir einen (kostenlosen) Cloud Dienst (z.B. google colab) zu suchen, denn 6GB für's Training ist schon hart an der Grenze. Viel Erfolg!

**Comment by ichessebaeume1** [comment]
Vielen Dank! Ich werde es gleich ausprobieren!
