### ISSUE TITLE
synthesizer not loading

### ISSUE THREAD

**Issue by simteraplications** [padmalcom/Real-Time-Voice-Cloning-German#4]
Hello. I have just triede to import the german model but i think there is a missing file in the release folder. I get the following output when trying to run the toolbox.

2021-04-12 22:16:49.835355: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2021-04-12 22:16:49.835449: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
C:\Users\HP\Downloads\Real-Time-Voice-Cloning-master\Real-Time-Voice-Cloning-master\encoder\audio.py:13: UserWarning: Unable to import 'webrtcvad'. This package enables noise removal and is recommended.
  warn("Unable to import 'webrtcvad'. This package enables noise removal and is recommended.")
Warning: you did not pass a root directory for datasets as argument.
The recognized datasets are:
	LibriSpeech/dev-clean
	LibriSpeech/dev-other
	LibriSpeech/test-clean
	LibriSpeech/test-other
	LibriSpeech/train-clean-100
	LibriSpeech/train-clean-360
	LibriSpeech/train-other-500
	LibriTTS/dev-clean
	LibriTTS/dev-other
	LibriTTS/test-clean
	LibriTTS/test-other
	LibriTTS/train-clean-100
	LibriTTS/train-clean-360
	LibriTTS/train-other-500
	LJSpeech-1.1
	VoxCeleb1/wav
	VoxCeleb1/test_wav
	VoxCeleb2/dev/aac
	VoxCeleb2/test/aac
	VCTK-Corpus/wav48
Feel free to add your own. You can still use the toolbox by recording samples yourself.
Traceback (most recent call last):
  File "sv2tts.py", line 43, in <module>
    Toolbox(**vars(args))
  File "C:\Users\HP\Downloads\Real-Time-Voice-Cloning-master\Real-Time-Voice-Cloning-master\toolbox\__init__.py", line 72, in __init__
    self.reset_ui(enc_models_dir, syn_models_dir, voc_models_dir, seed)
  File "C:\Users\HP\Downloads\Real-Time-Voice-Cloning-master\Real-Time-Voice-Cloning-master\toolbox\__init__.py", line 140, in reset_ui
    self.ui.populate_models(encoder_models_dir, synthesizer_models_dir, vocoder_models_dir)
  File "C:\Users\HP\Downloads\Real-Time-Voice-Cloning-master\Real-Time-Voice-Cloning-master\toolbox\ui.py", line 340, in populate_models
    raise Exception("No synthesizer models found in %s" % synthesizer_models_dir)
Exception: No synthesizer models found in synthesizer\saved_models

I also looked in the dir and compared it to the dir of the english model and it also looks different for an example in the english model i have a folder synthesizer/saved_models/pretrained/pretrained.pt. How ever in the german one i have a folder called logs-my_run and a whole different file structure. Am i missing something or did i just get a broken file?

**Comment by padmalcom** [comment]
What exactly did you do? Did you copy over the files from the "Release 1" (right side of github repo) over the original repository?

**Comment by simteraplications** [comment]
Yes, i did exactly that, as you described it.

**Comment by padmalcom** [comment]
It seems to be more complicated to set up than I tought. I'd probably do a video tutorial in the next days.

**Comment by simteraplications** [comment]
can you plesae then also speak in the tutorial, like say what you are doing or in text form? I am blind so this would be really apreciated.

**Comment by padmalcom** [comment]
Of course I can. Let's talk about your usecase when you got it running!

**Comment by simteraplications** [comment]
youtube videos or just messing arround.

**Comment by NiklasHoltmeyer** [comment]
> It seems to be more complicated to set up than I tought. I'd probably do a video tutorial in the next days.

if you do that tutorial. please @niklasholtmeyer me, so that i can see your video! im very intrested in trying your model

**Comment by padmalcom** [comment]
I updated code and models in release 2, please use them instead of the old release and tell me if it works.

**Comment by padmalcom** [comment]
Okay I'm closing this one since I could verify that loading the synthesizer works as trained/designed with new models and the last push.
