### ISSUE TITLE
Request for German Male

### ISSUE THREAD

**Issue by ChrisDelClea** [padmalcom/Real-Time-Voice-Cloning-German#5]
Hey @padmalcom,

thanks for the training of the model and adapting to German. 
I saw the closed issue (Voice cloning of males not reflected in result). 
In it you said you might retrain it to work for German male as well.
I am curious if you had a chance to do so? 

Also I wanted to know if one could use pretrained models (German versions) Encoder, Synthesizer and Vocoder 
on the original demo_toolbox.py in some way? Could you share these maybe? 

Best regards 
Chris

**Comment by padmalcom** [comment]
Hi Chris,
male voices are in the making - not now, but in the next days. Yes of course you can run the in the toolbox, just add "my_run.pt" (file) to encoder\saved_models, "logs-my_run" (folder) to synthesizer\saved_models and "my_run" (folder) to vocoder\saved_models

**Comment by ChrisDelClea** [comment]
Hi @padmalcom,
Would be great if you notify me if it's possible :)
thanks you.

**Comment by padmalcom** [comment]
@ChrisChross You can watch this repository in the top right corner when selecting "All Activity"
