### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by GenericGitGuy** [padmalcom/Real-Time-Voice-Cloning-German#7]
Hi, please excuse if i sound like a total noob, but this is all relatively new to me.
So, i have your repo and the original real time voice cloning toolbox. How can i now combine both to clone a german voice? Or do i understand something wrong concerning the goal of your project? 
On the git page, it says that it is a german model for the voice cloning toolbox, so i would expect that it provides a trained encoder, synthesizer and vocoder which i can copy into the corresponding directories in the original toolbox. But inside your directories are only two python scripts which refer to some datasets. Do i need to train the encoder and the synthesizer myself? If yes so, what kind of data would i need?
Also, in one of the closed issues you write "yes of course you can run the in the toolbox, just add "my_run.pt" (file) to encoder\saved_models, "logs-my_run" (folder) to synthesizer\saved_models and "my_run" (folder) to vocoder\saved_models", but i cant find any file named "my_run.pt", no "logs-my_run" folder and no "my_run" folder? Will these be generated during the training?
I guess you can see that i am a little bit confused about how all of this works and i hope that you might be able to help me here.
Thank you for your time!

**Comment by padmalcom** [comment]
Hi @GenericGitGuy,
on the right of my repo you see the Releases. Use release 2 to download my pretrained models. Place these in the original repo of corentin. Then update all files in the original repo with the files in my repository. Then you can run the toolbox, select the "my_run" models for encoder, synthesizer and vocoder and clone German voices.
