### ISSUE TITLE
low_mem positional argument

### ISSUE THREAD

**Issue by technicaldirector** [padmalcom/Real-Time-Voice-Cloning-German#8]
Hey, 
first of all, thanks for your work!

I've tried to install this package but sadly it doesn't start.

My installation process: 
1. Replace the main files with your ones
2. Place your synthesizer, vocoder and endcoder into the folders
3. Start toolbox "python demo_toolbox.py"

But sadly I'm getting this error message:
`Traceback (most recent call last):
  File "demo_toolbox.py", line 43, in <module>
    Toolbox(**vars(args))
TypeError: __init__() missing 1 required positional argument: 'low_mem'`

Any ways to fix that?

Best, Justus

**Comment by padmalcom** [comment]
Hi Justus, there were many new commits in the main repository so that parameters do not match anymore. I'm working on an update right now and will update files and models in the next few days.
When you really want to fix that issue now, look what low_mem is used for and simply add it to _args_.

**Comment by technicaldirector** [comment]
Hey padmalcom,
thanks for your answer! I've tried to solve this error but to be honest... I wasn't able to fix that :D
(I'm more into web developement and javascript then py ^^)

I think I'm going to wait :)

Thanks

**Comment by MrRoxMCArthur** [comment]
@padmalcom thank you very much for sharing your work :). Like @MrBukkitGamer described i had the same problem. So I used a default value for "low_mem". The application is running but it is not possible to "Synthesize and vocode". 

I like to create own voice assets for games. Not to use it for commercial stuff, just to know how the result would be.

Is it possible to explain which datasets are in "E/Datasets/"?  In the english version "LibriSpeech" with "train-clean-100" are located there. Right now my Dataset folder "for german" is empty. 

Best regards and again thank you very much :)

**Comment by padmalcom** [comment]
Hi @MrBukkitGamer I fixed the lol_mem issue in the __init__.py in the toolbox folder. Have a look and tell me if it solves your issue please.

**Comment by technicaldirector** [comment]
Sounds great! 
I'm going to have a look at it in the next days :)

Thanks
