### ISSUE TITLE
shape error in training synthesizer

### ISSUE THREAD

**Issue by Bebaam** [padmalcom/Real-Time-Voice-Cloning-German#9]
Hey Padmalcom,
I am trying to train a german model, too. I used Corentins git and the dataset of CommonVoice.
At the moment, I trained around 260k steps of synthesizer with a batch_size of 6 and a loss of around 0.57 now, with nearly no results right now (Did not touch encoder yet).

I was trying to use your code now to see your #steps and the loss you get, but I am not able to test it, could you share that please ? 

I get a similar problem as in another issue, namely:
`RuntimeError: Error(s) in loading state_dict for Tacotron:                                                                      size mismatch for encoder.embedding.weight: copying a param with shape torch.Size([66, 512]) from checkpoint, the shape in current model is torch.Size([73, 512]).`

I also used your recommended commit of corentins and also copied your modified files into it. But error is still there.
There was an error with similar issue, but I used the right symbols.py which you uploaded recently.
https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/779

So is the encoder here the matching one? 

Thanks for your help in advance.

**Comment by padmalcom** [comment]
Hi Bebaam, I'm currently updating code and models because there were so many changes in the original repository. Please wait some more days, I'll update releases and instructions soon.

**Comment by MrRoxMCArthur** [comment]
Hi @padmalcom  thanks alot for sharing your project with us :). Unfortunately i have the same issues liked Bebaam discussed above.

**Comment by padmalcom** [comment]
I'm closing this, since it is a duplicate to https://github.com/padmalcom/Real-Time-Voice-Cloning-German/issues/3
